In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,100,(10,10))
print(a)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.ndim)

[[79 20 28 68 29 53 66 35 25 64]
 [63 23 43 10 26 70 33 64 52  5]
 [77 87 71 15 79 62 25 71 23 41]
 [60 32 39 12 89 75 97 41 20 19]
 [63 16 24 66 23 25 49 74 48 46]
 [19 24 18  8 60 26 87 62 35 67]
 [58 28 89 63 97 38 89 86 96 15]
 [15 42 21 57 43 51 56 63 25 69]
 [57 21 97 35  3 94 77 73 35 57]
 [ 3 24 53 89 40 80 43 72 22 72]]
(10, 10)
100
int32
4
2


In [5]:
a=np.arange(20)
r=a.reshape(4,5)
rr=a.reshape(10,2)
print(r)
print(rr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [11]:
a=np.random.randn(5,5)
a.astype(float)
a[a<0.5]=0
print(a)

[[0.         0.         0.84330516 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.78530457 0.         1.23427066]
 [0.         0.70432863 0.86077665 0.         0.        ]
 [1.61026258 1.2282651  0.         1.38723618 1.835728  ]]


In [13]:
a=np.random.randint(1,101,100)
print(a)
u=np.unique(a)
print(u)

[ 82   1  20  75  81  95  39  94  49  23  84  38  41  44  45   2  24   8
  52  10  17  46  12  91  99  27  50  86  61  52  99  25  57  99  68  62
   8   2  89  48  57  74 100  29   5  89  68  13  80  63  20  48  92  68
   4  37  18  70  31  91  59  94  49  28  11  47  87  72  66  12  39  29
  55  39  28   9  20  95  52  64  16  85  71  84  63  37  84  39  59  95
  22  47  27  85   5  57  56  85  68  68]
[  1   2   4   5   8   9  10  11  12  13  16  17  18  20  22  23  24  25
  27  28  29  31  37  38  39  41  44  45  46  47  48  49  50  52  55  56
  57  59  61  62  63  64  66  68  70  71  72  74  75  80  81  82  84  85
  86  87  89  91  92  94  95  99 100]


In [16]:
a=np.eye(7)
print(a)
a[np.diag_indices(7)]=np.random.randint(1,10,7)
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[4. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 7.]]


In [17]:
dices=np.random.randint(1,7,10)
print("first array:",dices)
values,frequencies=np.unique(dices,return_counts=True)
print("frequencies:")
for value,frequency in zip(values,frequencies):
    print(value,":",frequency)

first array: [2 4 5 2 4 4 1 4 4 5]
frequencies:
1 : 1
2 : 2
4 : 5
5 : 2


In [20]:
a=np.random.randint(1,50,20)
print("array:",a)
parts=np.split(a,4)
print("subarray:")
for part in parts:
    print(part)


array: [34 10 15 17 14  9  9 44 21 35 29 17 24 15 26 24 20 40 31 19]
subarray:
[34 10 15 17 14]
[ 9  9 44 21 35]
[29 17 24 15 26]
[24 20 40 31 19]


In [22]:
a=np.random.randint(1,20,(6,6))
print("elements:",a)
n=a[a>10]
print("greater than:",n)

elements: [[ 6  2  2 17  3  2]
 [16  2 10  2  9  4]
 [18 19  7 11 19  4]
 [10  4  5 16  2  8]
 [15 18 17 18  6  5]
 [ 1 15  8  5  5 14]]
greater than: [17 16 18 19 11 19 16 15 18 17 18 15 14]


In [29]:
a=np.array([10,20,30,40,50,60])
print("array:",a)
v=a.view()
print("slice:",a[0:4])
a[0]=-1
print("view:",a)
c=a.copy()
a[0]=100
print("copy:",a)

array: [10 20 30 40 50 60]
slice: [10 20 30 40]
view: [-1 20 30 40 50 60]
copy: [100  20  30  40  50  60]


In [30]:
a=np.random.randint(0,9,(3,3,3))
print(a.shape)
r=a.reshape(9,3)
print(r)


(3, 3, 3)
[[4 3 0]
 [8 5 3]
 [2 7 5]
 [5 2 7]
 [8 0 6]
 [4 7 2]
 [2 5 2]
 [6 4 3]
 [7 1 2]]


In [35]:
a=np.arange(1,101).reshape(10,10)
border=np.concatenate([
a[0,:],
a[-1,:],
a[1:-1,0],
a[1:-1,-1]
])
print("array:",a)
print("border:",border)

array: [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
border: [  1   2   3   4   5   6   7   8   9  10  91  92  93  94  95  96  97  98
  99 100  11  21  31  41  51  61  71  81  20  30  40  50  60  70  80  90]


In [37]:
a=np.arange(1,101).reshape(10,10)
row=np.arange(10)
cols=np.arange(10)
diagonal=a[row,cols]
print(a)
print("diagonal:",diagonal)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
diagonal: [  1  12  23  34  45  56  67  78  89 100]


In [40]:
a=np.arange(64).reshape(4,4,4)
i,j,k=np.indices(a.shape)
result=a[(i+j+k)%2==0]
print(result)

[ 0  2  5  7  8 10 13 15 17 19 20 22 25 27 28 30 32 34 37 39 40 42 45 47
 49 51 52 54 57 59 60 62]
