In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
10
int64
8


In [3]:
a=np.arange(0,21,2)
print(a)
print(a.shape)

[ 0  2  4  6  8 10 12 14 16 18 20]
(11,)


In [6]:
a=np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [7]:
a=np.ones((4,4))
print(a)
print(a.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [9]:
a=np.zeros((3,3))
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(3, 3)
float64


In [10]:
a=np.full((2,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [11]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
a=np.random.rand(5)
print(a)

[0.22012118 0.56401622 0.89801569 0.42433767 0.88906335]


In [16]:
a=np.random.rand(5)
print(a)

[0.40201786 0.48778105 0.95718596 0.77264274 0.47923471]


In [17]:
a=np.random.randn(3,3)
print(a)

[[ 0.64921011  0.22097433  0.94181347]
 [-1.24641303  0.29698576 -0.20492698]
 [ 0.46108869  1.15015965 -0.79693129]]


In [18]:
a=np.random.randint(10,50,10)
print(a)

[33 20 44 14 24 38 44 43 21 41]


In [19]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[1 2 3 4 5 6]
1
(6,)
6


In [23]:
a=np.random.randint(1,100,size=(2,4))
print(a)
print(a.dtype)

[[76  8 66 74]
 [93 36  7 36]]
int32


In [26]:
a=np.array([1,2,3,4,5])
b=a.copy()
b[0]=8
print(a)
print(b)

[1 2 3 4 5]
[8 2 3 4 5]


In [29]:
b=np.array([10,20,30,40,50])
c=b.view()
c[1]=4
print(b)
print(c)


[10  4 30 40 50]
[10  4 30 40 50]


In [30]:
a=np.arange(100,120)
print(a)
print(a.shape)
print(a.size)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]
(20,)
20


In [31]:
a=np.linspace(0,1,15)
print(a)


[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


In [34]:
a=np.ones((2,3),dtype=int)
print(a)
print(a.dtype)

[[1 1 1]
 [1 1 1]]
int64


In [39]:
a=np.zeros((3,3),dtype=float)
print(a)
print(a.itemsize)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
8


In [47]:
a=np.random.randint(0,10,size=(2,5))
print(a)
print(a.shape)

[[7 4 9 6 1]
 [2 3 7 7 6]]
(2, 5)


In [1]:
import numpy as np

In [9]:
a=np.arange(10)
ind=a[2]
print(ind)

2


In [15]:
a=np.arange(10)
print("array:",a)
print(a[2])

array: [0 1 2 3 4 5 6 7 8 9]
2


In [16]:
a=np.arange(10,20)
print("array:",a)
s=a[2:8]
print("slice:",s)

array: [10 11 12 13 14 15 16 17 18 19]
slice: [12 13 14 15 16 17]


In [22]:
a=np.arange(0,21)
print("array:",a)
i=a[5:]
print("elements:",i)

array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
elements: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
a=np.arange(0,21)
print("array:",a)
s=a[:5]
print("slice:",s)

array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
slice: [0 1 2 3 4]


In [25]:
a=np.arange(1,11)
print("array:",a)
r=a[-1]
print("reverse:",r)

array: [ 1  2  3  4  5  6  7  8  9 10]
reverse: 10


In [27]:
a=np.arange(1,11)
print("array:",a)
r=a[-3:]
print("reverse:",r)

array: [ 1  2  3  4  5  6  7  8  9 10]
reverse: [ 8  9 10]


In [29]:
a=np.arange(1,10).reshape(3,3)
print("array:",a)
rc=a[1,2]
print(rc)

array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [40]:
a=np.arange(1,10).reshape(3,3)
print("array:",a)
rc=a[1]
print("row:",rc)

array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
row: [4 5 6]


In [44]:
a=np.arange(1,10).reshape(3,3)
print("array:",a)
rc=a[:,2]
print("col:",rc)

array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
col: [3 6 9]


In [47]:
a=np.arange(1,10).reshape(3,3)
print("array:",a)
submatrix=a[0:2,0:2]
print("first two row and two column:",submatrix)

array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
first two row and two column: [[1 2]
 [4 5]]


In [48]:
a=np.arange(24).reshape(2,3,4)
print("array:",a)
i= a[1,2,3]
print("index:",i)

array: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
index: 23


In [55]:
a=np.arange(27).reshape(3,3,3)
print("array:",a)


array: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
