In [3]:
import numpy as np

In [4]:
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [16]:
a=np.array([[1,2,3],
            [4,5,6]])
print(a)
print(a.shape)
print(a.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [17]:
a=np.array([[[1,2],
             [3,4],
             [5,6],
             [7,8]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3
(1, 4, 2)
8


In [13]:
a=np.zeros(10)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
(10,)
10


In [20]:
a=np.array([[0,0,0,0],
           [0,0,0,0],
           [0,0,0,0]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 4)
12


In [24]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b=(a.reshape(3,4))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)
12


In [26]:
a=np.arange(1,10).reshape(3,3)
print("array:")
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


In [27]:
a=np.arange(10,31)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
1
(21,)
21


In [28]:
a=np.array([[10,20,30],
            [40,50,60],
            [70,80,90]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
(3, 3)
9


In [29]:
a=np.arange(1,21).reshape(4,5)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2
(4, 5)
20


In [30]:
a=np.arange(1,13).reshape(2,2,3)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12


In [3]:
import numpy as np

In [4]:
a=np.arange(5,51,5)
print(a)

[ 5 10 15 20 25 30 35 40 45 50]


In [7]:
a=np.ones((4,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
a=np.linspace(0,1,6)
print(a)


[0.  0.2 0.4 0.6 0.8 1. ]


In [11]:
a=np.linspace(10,31,5)
print(a)

[10.   15.25 20.5  25.75 31.  ]


In [14]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
a=np.array([10,20,30,40,50])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[10 20 30 40 50]
1
(5,)
5
int64


In [20]:
lst=[10,20,30,40,50]
a=np.array(lst)
print(a)

[10 20 30 40 50]


In [23]:
a=np.arange(1,17)
matrix=a.reshape(4,4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
a=np.array([10,20,30,40,50])
print(a[2])


30


In [32]:
a=np.array([20,30,39,11,20,20,59])
middle_element=a[len(a)//2]
print(middle_element)

11


In [29]:
a=np.array([10,30,40,20,50])
print(a[::-1])

[50 20 40 30 10]


In [31]:
a=np.array([10,40,34,20,44])
print(a[a>25])

[40 34 44]


In [34]:
a=np.array([-7,-8,-5,5,2,-3])
a[a<0]=0
print(a)

[0 0 0 5 2 0]


In [40]:
a=np.array([20,30,39,11,20,20,59])
print(a[a%3==0])


[30 39]


In [42]:
a=np.array([20,30,39,11,20,20,59])
print(np.mean(a))

28.428571428571427


In [43]:
a=np.array([20,30,39,11,20,20,59])
print(np.where(a==20))

(array([0, 4, 5]),)


In [44]:
a=np.array([20,30,39,11,20,20,59])
b=a+10
print(b)

[30 40 49 21 30 30 69]


In [47]:
a=np.array([[1,2,3],
            [4,5,6]])
a2=np.array([10,20,30])
result=a+a2
print(result)

[[11 22 33]
 [14 25 36]]
