In [3]:
import numpy as np

In [4]:
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [16]:
a=np.array([[1,2,3],
            [4,5,6]])
print(a)
print(a.shape)
print(a.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [17]:
a=np.array([[[1,2],
             [3,4],
             [5,6],
             [7,8]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3
(1, 4, 2)
8


In [13]:
a=np.zeros(10)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
(10,)
10


In [20]:
a=np.array([[0,0,0,0],
           [0,0,0,0],
           [0,0,0,0]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 4)
12


In [24]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b=(a.reshape(3,4))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)
12


In [26]:
a=np.arange(1,10).reshape(3,3)
print("array:")
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


In [27]:
a=np.arange(10,31)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
1
(21,)
21


In [28]:
a=np.array([[10,20,30],
            [40,50,60],
            [70,80,90]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
(3, 3)
9


In [29]:
a=np.arange(1,21).reshape(4,5)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2
(4, 5)
20


In [30]:
a=np.arange(1,13).reshape(2,2,3)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
