In [1]:
import numpy as np

In [10]:
b=np.random.randint(10,100,size=(4,4))
print(b)
print(b.ndim)
print(b.itemsize)
print(b.size)
print(b.dtype)
print(b.shape)

[[84 71 58 72]
 [12 43 34 73]
 [32 15 87 63]
 [91 56 10 38]]
2
4
16
int32
(4, 4)


In [11]:
a=np.random.randint(1,51,size=(3,5))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[45 36 23 23 37]
 [28  7 12 29  8]
 [26 41  8 49 28]]
2
(3, 5)
15
int32


In [12]:
a=np.random.randint(10,100,size=(2,4))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 4)
8
int32


In [14]:
a=np.arange(10,51,5)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)


[10 15 20 25 30 35 40 45 50]
1
(9,)
9
int64
8


In [19]:
a=np.zeros((3,3),dtype=int)
print(a)
print(a.dtype)
print(a.shape)
print(a.size)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64
(3, 3)
9


In [1]:
import numpy as np

In [3]:
a=np.random.randint(10,100,size=(4,4))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.dtype)

[[96 25 35 66]
 [28 67 69 27]
 [50 64 84 83]
 [25 71 54 83]]
2
(4, 4)
16
4
int32


In [5]:
a=np.arange(1,21)
b=a.reshape(4,5)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
a=np.linspace(-5,5,25)
b=a.reshape(5,5)
print(b)

[[-5.         -4.58333333 -4.16666667 -3.75       -3.33333333]
 [-2.91666667 -2.5        -2.08333333 -1.66666667 -1.25      ]
 [-0.83333333 -0.41666667  0.          0.41666667  0.83333333]
 [ 1.25        1.66666667  2.08333333  2.5         2.91666667]
 [ 3.33333333  3.75        4.16666667  4.58333333  5.        ]]


In [10]:
a=np.eye(6)
print(a)
diagonal=np.diag(a)
print(diagonal==1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[ True  True  True  True  True  True]


In [18]:
a=np.random.rand(3,3)
b=a.astype(float)
print(b)

[[0.11026794 0.26630013 0.58073434]
 [0.31570121 0.75855261 0.55448956]
 [0.64651957 0.74255003 0.1047735 ]]


In [29]:
a=np.random.randint(1,50,size=(5,5))
print(a)
print(a[0,:])
print(a[:,4])

[[41 46 34 18 12]
 [ 7 42 26 19  4]
 [38 10 30  6 29]
 [ 8 38 24 46 47]
 [ 2 15 23  7 24]]
[41 46 34 18 12]
[12  4 29 47 24]


In [2]:
import numpy as np

In [10]:
a=np.random.randint(1,50,size=(5,5))
print(a)
print("first row:",a[:,0])
print("last column:",a[4,:])

[[ 9 36 32  6 10]
 [27 32  5 43 23]
 [ 6  5 26 33  2]
 [44 26 21  2  7]
 [35 31 41 20 17]]
first row: [ 9 27  6 44 35]
last column: [35 31 41 20 17]


In [17]:
a=np.arange(20)
b=a.copy()
b[:5]=100
print(a)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [19]:
a=np.arange(10,60,5)
b=a.view()
b[-3:]=-1
print(a)
print(b)

[10 15 20 25 30 35 40 -1 -1 -1]
[10 15 20 25 30 35 40 -1 -1 -1]


In [27]:
a=np.ones((3,3))
result=a*7
print(a)
print(result)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [28]:
a=np.ones((3,3))
b=np.multiply(a,7)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [32]:
a=np.zeros((4,4))
np.fill_diagonal(a,9)
print(a)

[[9. 0. 0. 0.]
 [0. 9. 0. 0.]
 [0. 0. 9. 0.]
 [0. 0. 0. 9.]]


In [43]:
a=np.random.randint(10,99,size=(5,5))
sub=a[:2,:2]
print(a)
print(sub)

[[79 30 88 60 86]
 [97 16 81 10 52]
 [49 37 22 87 49]
 [37 23 26 42 88]
 [90 69 24 53 43]]
[[79 30]
 [97 16]]


In [49]:
a=np.random.randint(1,100,12)
b=a.reshape(3,4)
print(a)
print(b)
print(b.T)


[70 69 11 16  4 16 77 71 59 71  2 52]
[[70 69 11 16]
 [ 4 16 77 71]
 [59 71  2 52]]
[[70  4 59]
 [69 16 71]
 [11 77  2]
 [16 71 52]]


In [6]:
import numpy as np

In [7]:
a=np.arange(1,51)
even=a[a%2==0]
print(even)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [14]:
a=np.random.randint(1,21,10)
print(a)
a[a>10]=0
print("updated array:",a)

[ 5  1 12 14  2 16 10  1  9  2]
updated array: [ 5  1  0  0  2  0 10  1  9  2]


In [18]:
a=np.random.randn(2,5)
a=np.round(a,2)
print(a)

[[ 1.48 -0.4  -0.7   0.38 -1.37]
 [ 0.65 -0.66 -1.82  0.02  0.28]]


In [23]:
a=np.random.randint(1,20,6)
b=a.astype(float)
print(a)
print(b)

[15  6  2 13 11  3]
[15.  6.  2. 13. 11.  3.]


In [24]:
a=np.linspace(1,100,9)
r=a.reshape(3,3)
print(r)

[[  1.     13.375  25.75 ]
 [ 38.125  50.5    62.875]
 [ 75.25   87.625 100.   ]]


In [27]:
a=np.linspace(1,100,9,dtype=int)
r=a.reshape(3,3)
print(r)

[[  1  13  25]
 [ 38  50  62]
 [ 75  87 100]]


In [31]:
a=np.random.randint(0,9,size=(4,4))
a[a%2!=0]=-1
print(a)

[[-1  6  4 -1]
 [ 6  2  4 -1]
 [-1  0  4  8]
 [-1  6 -1 -1]]


In [36]:
a=np.array([23,34,53,332,44,32])
b=a.copy()
a[0]=0
c=a.view()
a[1]=-1
print("original:",a)
print("copy:",b)
print("view:",c)

original: [  0  -1  53 332  44  32]
copy: [ 23  34  53 332  44  32]
view: [  0  -1  53 332  44  32]


In [41]:
a=np.random.randint(2,20,(2,6))
print("normal array:",a)
print("ravel array:",a.ravel())
print("flatten:",a.flatten())

normal array: [[11 15 17 12  9 17]
 [ 3 12 17 15 14 19]]
ravel array: [11 15 17 12  9 17  3 12 17 15 14 19]
flatten: [11 15 17 12  9 17  3 12 17 15 14 19]


In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,101,(10,10))
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.itemsize)

[[ 78  92  90   9  91  80  33  84  50   8]
 [ 83  86  73  92  79  79  79  65  37  53]
 [ 17  94  86  26   1  69  32  57  28  51]
 [ 56  73  97  15  15  22  98  82   8  92]
 [ 75  14  82  20  68  43  94  31  10  99]
 [  8  53  62  56  33   2  25  65  76  91]
 [  8  37  33  94  32  46   9  19 100  70]
 [ 30  53  53  40  34  34  80  42  67  19]
 [ 26  96  95  86  75  44   8  69   5   8]
 [ 21  47  15  46  14  88  77  89  58  40]]
2
(10, 10)
int32
100
4


In [3]:
a=np.arange(1,21)
b=a.reshape(4,5)
c=a.reshape(10,2)
print(a)
print(b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [6]:
a=np.random.randn(5,5)
a[a<0.5]=0
print(a)

[[0.59162282 0.         0.         0.         0.        ]
 [0.         0.         0.610199   0.83589809 0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.72744142 0.         0.         2.33812251]
 [0.         0.         0.         0.         1.02656311]]


In [7]:
a=np.random.rand(5,5)
a[a<0.5]=0
print(a)

[[0.         0.90604614 0.         0.         0.        ]
 [0.         0.         0.         0.         0.51813696]
 [0.58997108 0.         0.51101213 0.         0.65144795]
 [0.         0.         0.         0.         0.76148474]
 [0.         0.         0.         0.         0.85631636]]


In [8]:
a=np.random.randint(1,101,100)
print(np.unique(a))

[  1   3   4   5   6   7   9  11  13  14  15  16  19  21  22  23  24  26
  28  29  30  31  33  34  35  36  37  38  39  42  43  46  47  48  49  51
  52  53  57  59  65  67  71  72  73  74  75  77  78  80  82  83  85  86
  88  91  92  93  94  95  96  97  99 100]


In [12]:
a=np.random.randint(1,101,(10,10))
print("random value:",a)
print("unique values:",np.unique(a))

random value: [[ 78  61  10  63  44  97  70   9  32  35]
 [ 10  96  20  72  32  89  94   8  92  99]
 [ 45  68  46  83  87  65  52  99  65   7]
 [ 88  79  54  95  90  55  18  49   2  84]
 [ 70  19  54  87  27  29  48  60  62  67]
 [ 96  30  35  40  77  86  77  37  14  11]
 [ 12  34  69  63  92  84   9  32  66  79]
 [ 42   8  89  90  90  52  19  46 100  97]
 [ 58  14  23  77  31  16  96  77  76  50]
 [ 93  49  38  40  13  33  24  38  31  67]]
unique values: [  2   7   8   9  10  11  12  13  14  16  18  19  20  23  24  27  29  30
  31  32  33  34  35  37  38  40  42  44  45  46  48  49  50  52  54  55
  58  60  61  62  63  65  66  67  68  69  70  72  76  77  78  79  83  84
  86  87  88  89  90  92  93  94  95  96  97  99 100]


In [22]:
a=np.eye(7)
a[np.diag_indices(7)]=np.random.randint(1,10,7)
print(a)

[[6. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 9.]]


In [28]:
rolls=np.random.randint(1,7,10)
print("rolls:",rolls)
values,frequencies=np.unique(rolls,return_counts=True)
print("frequencies:")
for value ,frequency in zip(values,frequencies):
    print(value,":",frequency)


rolls: [6 4 3 4 5 3 4 6 1 2]
frequencies:
1 : 1
2 : 1
3 : 2
4 : 3
5 : 1
6 : 2


In [29]:
rolls=np.random.randint(1,7,10)
print("rolls:",rolls)
values,frequencies=np.unique(rolls,return_counts=True)
print("frequencies:")
for value,frequency in zip(values,frequencies):
    print(value,":",frequency)

rolls: [2 2 4 3 5 2 4 1 6 3]
frequencies:
1 : 1
2 : 3
3 : 2
4 : 2
5 : 1
6 : 1


In [30]:
rolls=np.random.randint(1,7,10)
print("rolls:",rolls)
values,frequencies=np.unique(rolls,return_counts=True)
print("frequencies:")
for value,frequency in zip(values,frequencies):
    print(value,":",frequency)

rolls: [4 4 4 3 5 6 6 6 6 4]
frequencies:
3 : 1
4 : 4
5 : 1
6 : 4


In [39]:
r=np.random.randint(1,50,20)
print("original array:",r)
parts=np.split(r,4)
print("sub array:")
for part in parts:
    print(part)


original array: [10 49 32 18  3 37 40 20 17 24 30  4 44  1 29 44 44 23  7 36]
sub array:
[10 49 32 18  3]
[37 40 20 17 24]
[30  4 44  1 29]
[44 44 23  7 36]


In [42]:
r=np.random.randint(1,21,(6,6))
print("old array:",r)
n=r[r>10]
print("new array:",n)

old array: [[ 7 20  7  6  4  5]
 [16 10 18 20 11 15]
 [18  7  7 15 12  8]
 [12  8  6 12  1 10]
 [14  2  7 15 13 20]
 [13 18 12  9  8  1]]
new array: [20 16 18 20 11 15 18 15 12 12 12 14 15 13 20 13 18 12]


In [43]:
s=np.array([12,34,22,43,54,33,12])
print("array:",s)
c=s.copy()
c[0]=-1
print("copy:",c)
v=s.view()
v[-1]=1
print("view:",v)

array: [12 34 22 43 54 33 12]
copy: [-1 34 22 43 54 33 12]
view: [12 34 22 43 54 33  1]


In [52]:
array=np.array([10,20,30,40,50,60])
v=array[0:4]
v[0]=99
print("original array:",array)
print("view array:",v)
c=array[0:4].copy()
c[0]=1
print("copy array:",c)

original array: [99 20 30 40 50 60]
view array: [99 20 30 40]
copy array: [ 1 20 30 40]


In [60]:
m=np.random.randint(0,9,(3,3,3))
print("original array:",m)
print(m.shape)
r=m.reshape(9,3)
print("new array:",r)

original array: [[[0 2 2]
  [1 0 8]
  [4 3 1]]

 [[0 5 0]
  [6 5 8]
  [2 5 1]]

 [[6 7 3]
  [5 0 3]
  [5 3 8]]]
(3, 3, 3)
new array: [[0 2 2]
 [1 0 8]
 [4 3 1]
 [0 5 0]
 [6 5 8]
 [2 5 1]
 [6 7 3]
 [5 0 3]
 [5 3 8]]


In [1]:
import numpy as np

In [3]:
a=np.arange(50,101)
result=a[10:21:2]
print(result)

[60 62 64 66 68 70]


In [6]:
a=np.arange(50,101)
result=a[-10:]
print(result)

[ 91  92  93  94  95  96  97  98  99 100]


In [11]:
a=np.arange(1,26).reshape(5,5)
result=a[-1,:]
print(result)

[21 22 23 24 25]


In [15]:
a=np.arange(1,26).reshape(5,5)
print("array:",a)
result=a[:,0]
print(result)

array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  6 11 16 21]


In [18]:
a=np.arange(1,26).reshape(5,5)
print("array:",a)
b=a[1:4,1:4]
print("submatrix:",b)

array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
submatrix: [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [26]:
a=np.arange(1,26).reshape(5,5)
print("array:",a)
result=a[0:5:2]
print(result)

array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [27]:
a=np.arange(1,26).reshape(5,5)
print("array:",a)
result=a[::2]
print(result)

array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [29]:
a=np.arange(1,26).reshape(5,5)
print("array:",a)
result=a[:,::2]
print("column:",result)

array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
column: [[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [33]:
a=np.arange(1,17).reshape(4,4)
print("array:",a)
result=a[[0,2]][:,[1,3]]
print("rows and cols:",result)

array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
rows and cols: [[ 2  4]
 [10 12]]


In [37]:
a=np.arange(1,28).reshape(3,3,3)
print("array:",a)
result=a[1,:,:]
print("second layer:",result)

array: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
second layer: [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [38]:
a=np.arange(1,28).reshape(3,3,3)
print("array:",a)
result=a[2,0,:]
print("last row:",result)

array: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
last row: [19 20 21]


In [39]:
a=np.arange(1,13).reshape(3,4)
print("array:",a)
result=a[:,::-1]
print("reverse:",result)

array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reverse: [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [40]:
a=np.arange(1,13).reshape(3,4)
print("array:",a)
result=a[::-1,::-1]
print("reverse:",result)


array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reverse: [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [43]:
a=np.arange(1,16)
print("array:",a)
id=a[a%3==0]
print("divisible:",id)

array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
divisible: [ 3  6  9 12 15]


In [46]:
a=np.arange(1,16)
print("array:",a)
result=a[(a>=5)&(a<=10)]
print("elements:",result)

array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
elements: [ 5  6  7  8  9 10]


In [48]:
a=np.random.randint(1,51,(4,4))
print("array:",a)
boolean=a[a>=25]
print("boolean:",boolean)

array: [[28 13 42 22]
 [11 40 11 43]
 [17 28 11 19]
 [24 45 20 24]]
boolean: [28 42 40 43 28 45]


In [51]:
a=np.array([5,10,15,20,25])
print("array:",a)
f=a[[4,3,2,1,0]]
print("fancy:",f)

array: [ 5 10 15 20 25]
fancy: [25 20 15 10  5]


In [52]:
a=np.array([5,10,15,20,25])
print("array:",a)
f=a[[1,1,4,4]]
print("duplicate:",f)

array: [ 5 10 15 20 25]
duplicate: [10 10 25 25]


In [53]:
a=np.arange(36).reshape(6,6)
print("array:",a)
check=a[::2,1::2]
print("even and odd :",check)

array: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
even and odd : [[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [57]:
a=np.arange(1,17).reshape(4,4)
print("array:",a)
f=a[[0,1,2,3],[1,2,3,0]]
print("fancy:",f)

array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
fancy: [ 2  7 12 13]


In [58]:
a=np.arange(1,11)
print("array:",a)
boolean=a[a%2 !=0]
fancy=a[[0,2,4,6,8]]
print("bool",boolean)
print("fancy",fancy)

array: [ 1  2  3  4  5  6  7  8  9 10]
bool [1 3 5 7 9]
fancy [1 3 5 7 9]
