In [1]:
import numpy as np
a = np.array([[10,20,30,40],
              [50,60,70,80]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
          

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
2
8


In [3]:
a = np.array([5,10,15.5,20])
print(a)
print(a.dtype)
print(a + 10 )

[ 5.  10.  15.5 20. ]
float64
[15.  20.  25.5 30. ]


In [4]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [5]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
a = np.full((3,3),100)
print(a)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [8]:
a = np.eye(4)*5
print(a)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [11]:
a = np.arange(1,10)
print(a)
print(a.sum())
print(a.shape)

[1 2 3 4 5 6 7 8 9]
45
(9,)


In [13]:
a = np.arange(1,13)
b= a.reshape(3,4)
print(a)
print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [15]:
a = np.arange(1,13).reshape(3,4)
print(a)
print(a.shape)
print(a.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(3, 4)


In [18]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.sum(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [19]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [22]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.max(axis=0))
print(a.min(axis=0))
print(a.max(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[1 2 3]
[3 6 9]


In [26]:
a = np.array([[10,20,30],
               [40,50,60]])
print(a)
print(a[1,2])

[[10 20 30]
 [40 50 60]]
60


In [27]:
a = np.array([10,20,"30"])
print(a[0] + a[1])

1020


In [31]:
a = np.array([12,45,2,67,89,34,18])
b = a[(a>30) & (a<80)]
print(b)

[45 67 34]


In [34]:
a = np.arange(1,17).reshape(4,4)
print("array",a)
a[(a%2 != 0)] = -1
print("filter",a)

array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
filter [[-1  2 -1  4]
 [-1  6 -1  8]
 [-1 10 -1 12]
 [-1 14 -1 16]]


In [35]:
a = np.arange(1,17).reshape(4,4)
print("array",a)
a [ a%2 == 0] = 2
print("even filter" , a)

array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
even filter [[ 1  2  3  2]
 [ 5  2  7  2]
 [ 9  2 11  2]
 [13  2 15  2]]


In [36]:
a = np.arange(1,26).reshape(5,5)
print("array" , a)
slice_1 = a[-2:,-2:]
print(slice_1)

array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[19 20]
 [24 25]]


In [37]:
a = np.arange(1,26).reshape(5,5)
print("array" , a)
slice_1 = a[3:,3:]
print(slice_1)

array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[19 20]
 [24 25]]


In [38]:
a = np.arange(1,25).reshape(4,-1)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [41]:
a = np.array([1,2,3])
b = np.array([4,5,6])
v_stack = np.vstack((a,b))
print(v_stack)

[[1 2 3]
 [4 5 6]]


In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
h_stack = np.hstack((a,b))
print(h_stack)

[1 2 3 4 5 6]


In [12]:
sales_data = np.array([[200, 450, 300], [600, 150, 800], [350, 500,
250]])
print("sales",sales_data)
row_maxima=np.max(sales_data,axis=1)
average = np.mean(row_maxima)
print("row_maxima",row_maxima)
print("average",average)

sales [[200 450 300]
 [600 150 800]
 [350 500 250]]
row_maxima [450 800 500]
average 583.3333333333334


In [13]:
dataset = np.array([120, np.nan, 250, 310, np.nan, 420, 190]) 
mean_value = np.nanmean(dataset)
replace_value = np.where(np.isnan(dataset) ,mean_value ,dataset)
print("dataset",dataset)
print("mean=",mean_value)
print("replace=",replace_value)

dataset [120.  nan 250. 310.  nan 420. 190.]
mean= 258.0
replace= [120. 258. 250. 310. 258. 420. 190.]


In [32]:
marks = np.array([45, 82, 67, 39, 91, 55, 74])
grade = np.where(marks>=50 ,"pass","fail")
print("marks=",marks)
print("grade=",grade)

marks= [45 82 67 39 91 55 74]
grade= ['fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'pass']


In [35]:
perf = np.array([3, 1, 5, 2, 4, 5, 3, 1, 4]) 
values,counts = np.unique(perf,return_counts = True)
all_values = values[counts == counts.max()]
print("all values = " ,all_values)

all values =  [1 3 4 5]


In [40]:
A = np.array([[10, 20], [30, 40]]) 
B = np.array([[5, 15], [25,35]])
stack = np.hstack((A,B))
result = np.ravel(stack)
print("stack",stack)
print("rev",result)

stack [[10 20  5 15]
 [30 40 25 35]]
rev [10 20  5 15 30 40 25 35]


In [41]:
np.random.seed(42)
arr = np.random.randint(100,500,20)
print(arr)

[202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357]


In [42]:
np.random.seed(42)
arr = np.random.randint(100,500,20)
print(arr)

[202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357]


In [43]:
np.random.seed(42)
arr = np.random.randint(100,500,20)
print(arr)

[202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357]


In [46]:
np.random.seed(42)
arr = np.random.randint(100,500,21)
indices_values = np.where(arr >= 300)
print("array=",arr)
print("index_position=",indices_values)

array= [202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357 443]
index_position= (array([ 1,  2,  9, 10, 12, 14, 18, 19, 20]),)


In [50]:
np.random.seed(42)
arr = np.random.randint(100,500,21)
indices_values = np.where(arr >= 300)[0]
elements = arr[indices_values]
print("array=",arr)
print("index_position=",indices_values)
print("Elements=",elements)

array= [202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357 443]
index_position= [ 1  2  9 10 12 14 18 19 20]
Elements= [448 370 314 430 472 459 408 357 443]


In [7]:
tx = np.array([[10, 20, 15,30], [5, 25, 35, 20], [40, 10, 50, 15]])
row_mean = np.mean(tx,axis=1,keepdims=True)
normalized_tx =  tx - row_mean 
print("text=",tx)
print("average=",row_mean)
print("normalization=",normalized_tx)

text= [[10 20 15 30]
 [ 5 25 35 20]
 [40 10 50 15]]
average= [[18.75]
 [21.25]
 [28.75]]
normalization= [[ -8.75   1.25  -3.75  11.25]
 [-16.25   3.75  13.75  -1.25]
 [ 11.25 -18.75  21.25 -13.75]]


In [14]:
prices = np.array([150, 80, 220, 110, 50, 300])
categories = np.array(['A', 'B','A', 'B', 'C', 'A']) 
values = prices[categories == "A"]
print("values of A = ",values)

values of A =  [150 220 300]


In [30]:
scores = np.array([450, 120, 890, 320, 670])
order = np.argsort(scores)[::-1]
highest = scores[order[:3]]
print(order)
print(highest)

[2 4 0 3 1]
[890 670 450]


In [32]:
arr = np.array([[10, 20, np.nan], [40, np.nan, 60], [70, 80,90]])
deviation = np.nanstd(arr , axis = 0)
print(arr)
print(deviation)

[[10. 20. nan]
 [40. nan 60.]
 [70. 80. 90.]]
[24.49489743 30.         15.        ]


In [38]:
np.random.seed(100)
chances = np.random.choice([1,0] , size = 100)
total_success = np.sum(chances)
print("chances=",chances)
print("total_success=",total_success)

chances= [1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1
 1 1 0 1 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 1]
total_success= 50


In [47]:
num = np.arange(1,26).reshape(5,5)
indices = np.arange(5)
diagonal_num = num[indices,indices]
print(num)
print("=",diagonal_num)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
= [ 1  7 13 19 25]


In [50]:
temp = np.array([32.5, 34.0, 29.8, 36.2, 31.0, 35.5])
temp_mean = np.mean(temp)
std_temp = np.std(temp)
z_score = (temp-temp_mean)/std_temp
print(z_score)

[-0.28952081  0.36190101 -1.46208007  1.31731966 -0.94094262  1.01332282]


In [53]:
a = np.arange(10)
b = a[2:7].copy()
b[0]=-1
print("a=",a)
print("b=",b)

a= [0 1 2 3 4 5 6 7 8 9]
b= [-1  3  4  5  6]


In [61]:
X = np.array([[1, 2, 3], [4, 5, 6]])
Y = np.array([[7, 8, 9], [10, 11,12]])
con = np.concatenate((X,Y))
rows = np.concatenate((X,Y),axis=1)
cols = np.concatenate((X,Y),axis =0 )
print("cols",cols)
print("rows=",rows)
print("=",con)

cols [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
rows= [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
filter_arr = (a > 20 ) & ( a < 70 )
a[filter_arr] = a[filter_arr] ** 2
print("a=",a)

a= [  10   20  900 1600 2500 3600   70   80]


In [42]:
a = np.eye(3) * 5
b = np.ones((3,3))
result = np.vstack((a,b))
print(result)

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
arr = np.array([1.2, np.nan, 3.8, 4.5, np.nan, 2.1]) 
clean_arr = arr[~np.isnan(arr)]
print(clean_arr)

[1.2 3.8 4.5 2.1]


In [49]:
a = np.linspace(0, 100, 10).astype(int)
values,counts = np.unique(a,return_counts =True)
print(len(values),counts)

10 [1 1 1 1 1 1 1 1 1 1]


In [51]:
data = np.array([[15, 88, 42], [91, 23, 67], [54, 76, 12]]) 
new_arr = np.where(data >= 50 ) == 1
print(new_arr)

False


In [52]:
data = np.array([[15, 88, 42], [91, 23, 67], [54, 76, 12]])
result = np.where(data>=50,1,0)
print(result)

[[0 1 0]
 [1 0 1]
 [1 1 0]]
