In [1]:
import numpy as np
a = np.array([[10,20,30,40],
              [50,60,70,80]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
          

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
2
8


In [3]:
a = np.array([5,10,15.5,20])
print(a)
print(a.dtype)
print(a + 10 )

[ 5.  10.  15.5 20. ]
float64
[15.  20.  25.5 30. ]


In [4]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [5]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
a = np.full((3,3),100)
print(a)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [8]:
a = np.eye(4)*5
print(a)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [11]:
a = np.arange(1,10)
print(a)
print(a.sum())
print(a.shape)

[1 2 3 4 5 6 7 8 9]
45
(9,)


In [13]:
a = np.arange(1,13)
b= a.reshape(3,4)
print(a)
print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [15]:
a = np.arange(1,13).reshape(3,4)
print(a)
print(a.shape)
print(a.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(3, 4)


In [18]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.sum(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [19]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [22]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.max(axis=0))
print(a.min(axis=0))
print(a.max(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[1 2 3]
[3 6 9]


In [26]:
a = np.array([[10,20,30],
               [40,50,60]])
print(a)
print(a[1,2])

[[10 20 30]
 [40 50 60]]
60


In [27]:
a = np.array([10,20,"30"])
print(a[0] + a[1])

1020


In [31]:
a = np.array([12,45,2,67,89,34,18])
b = a[(a>30) & (a<80)]
print(b)

[45 67 34]


In [34]:
a = np.arange(1,17).reshape(4,4)
print("array",a)
a[(a%2 != 0)] = -1
print("filter",a)

array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
filter [[-1  2 -1  4]
 [-1  6 -1  8]
 [-1 10 -1 12]
 [-1 14 -1 16]]


In [35]:
a = np.arange(1,17).reshape(4,4)
print("array",a)
a [ a%2 == 0] = 2
print("even filter" , a)

array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
even filter [[ 1  2  3  2]
 [ 5  2  7  2]
 [ 9  2 11  2]
 [13  2 15  2]]


In [36]:
a = np.arange(1,26).reshape(5,5)
print("array" , a)
slice_1 = a[-2:,-2:]
print(slice_1)

array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[19 20]
 [24 25]]


In [37]:
a = np.arange(1,26).reshape(5,5)
print("array" , a)
slice_1 = a[3:,3:]
print(slice_1)

array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[19 20]
 [24 25]]


In [38]:
a = np.arange(1,25).reshape(4,-1)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [41]:
a = np.array([1,2,3])
b = np.array([4,5,6])
v_stack = np.vstack((a,b))
print(v_stack)

[[1 2 3]
 [4 5 6]]


In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
h_stack = np.hstack((a,b))
print(h_stack)

[1 2 3 4 5 6]


In [12]:
sales_data = np.array([[200, 450, 300], [600, 150, 800], [350, 500,
250]])
print("sales",sales_data)
row_maxima=np.max(sales_data,axis=1)
average = np.mean(row_maxima)
print("row_maxima",row_maxima)
print("average",average)

sales [[200 450 300]
 [600 150 800]
 [350 500 250]]
row_maxima [450 800 500]
average 583.3333333333334


In [13]:
dataset = np.array([120, np.nan, 250, 310, np.nan, 420, 190]) 
mean_value = np.nanmean(dataset)
replace_value = np.where(np.isnan(dataset) ,mean_value ,dataset)
print("dataset",dataset)
print("mean=",mean_value)
print("replace=",replace_value)

dataset [120.  nan 250. 310.  nan 420. 190.]
mean= 258.0
replace= [120. 258. 250. 310. 258. 420. 190.]


In [32]:
marks = np.array([45, 82, 67, 39, 91, 55, 74])
grade = np.where(marks>=50 ,"pass","fail")
print("marks=",marks)
print("grade=",grade)

marks= [45 82 67 39 91 55 74]
grade= ['fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'pass']


In [35]:
perf = np.array([3, 1, 5, 2, 4, 5, 3, 1, 4]) 
values,counts = np.unique(perf,return_counts = True)
all_values = values[counts == counts.max()]
print("all values = " ,all_values)

all values =  [1 3 4 5]


In [40]:
A = np.array([[10, 20], [30, 40]]) 
B = np.array([[5, 15], [25,35]])
stack = np.hstack((A,B))
result = np.ravel(stack)
print("stack",stack)
print("rev",result)

stack [[10 20  5 15]
 [30 40 25 35]]
rev [10 20  5 15 30 40 25 35]


In [41]:
np.random.seed(42)
arr = np.random.randint(100,500,20)
print(arr)

[202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357]


In [42]:
np.random.seed(42)
arr = np.random.randint(100,500,20)
print(arr)

[202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357]


In [43]:
np.random.seed(42)
arr = np.random.randint(100,500,20)
print(arr)

[202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357]


In [46]:
np.random.seed(42)
arr = np.random.randint(100,500,21)
indices_values = np.where(arr >= 300)
print("array=",arr)
print("index_position=",indices_values)

array= [202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357 443]
index_position= (array([ 1,  2,  9, 10, 12, 14, 18, 19, 20]),)


In [50]:
np.random.seed(42)
arr = np.random.randint(100,500,21)
indices_values = np.where(arr >= 300)[0]
elements = arr[indices_values]
print("array=",arr)
print("index_position=",indices_values)
print("Elements=",elements)

array= [202 448 370 206 171 288 120 202 221 314 430 187 472 199 459 251 230 249
 408 357 443]
index_position= [ 1  2  9 10 12 14 18 19 20]
Elements= [448 370 314 430 472 459 408 357 443]


In [7]:
tx = np.array([[10, 20, 15,30], [5, 25, 35, 20], [40, 10, 50, 15]])
row_mean = np.mean(tx,axis=1,keepdims=True)
normalized_tx =  tx - row_mean 
print("text=",tx)
print("average=",row_mean)
print("normalization=",normalized_tx)

text= [[10 20 15 30]
 [ 5 25 35 20]
 [40 10 50 15]]
average= [[18.75]
 [21.25]
 [28.75]]
normalization= [[ -8.75   1.25  -3.75  11.25]
 [-16.25   3.75  13.75  -1.25]
 [ 11.25 -18.75  21.25 -13.75]]


In [14]:
prices = np.array([150, 80, 220, 110, 50, 300])
categories = np.array(['A', 'B','A', 'B', 'C', 'A']) 
values = prices[categories == "A"]
print("values of A = ",values)

values of A =  [150 220 300]


In [30]:
scores = np.array([450, 120, 890, 320, 670])
order = np.argsort(scores)[::-1]
highest = scores[order[:3]]
print(order)
print(highest)

[2 4 0 3 1]
[890 670 450]


In [32]:
arr = np.array([[10, 20, np.nan], [40, np.nan, 60], [70, 80,90]])
deviation = np.nanstd(arr , axis = 0)
print(arr)
print(deviation)

[[10. 20. nan]
 [40. nan 60.]
 [70. 80. 90.]]
[24.49489743 30.         15.        ]


In [38]:
np.random.seed(100)
chances = np.random.choice([1,0] , size = 100)
total_success = np.sum(chances)
print("chances=",chances)
print("total_success=",total_success)

chances= [1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1
 1 1 0 1 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 1]
total_success= 50


In [47]:
num = np.arange(1,26).reshape(5,5)
indices = np.arange(5)
diagonal_num = num[indices,indices]
print(num)
print("=",diagonal_num)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
= [ 1  7 13 19 25]


In [50]:
temp = np.array([32.5, 34.0, 29.8, 36.2, 31.0, 35.5])
temp_mean = np.mean(temp)
std_temp = np.std(temp)
z_score = (temp-temp_mean)/std_temp
print(z_score)

[-0.28952081  0.36190101 -1.46208007  1.31731966 -0.94094262  1.01332282]


In [53]:
a = np.arange(10)
b = a[2:7].copy()
b[0]=-1
print("a=",a)
print("b=",b)

a= [0 1 2 3 4 5 6 7 8 9]
b= [-1  3  4  5  6]


In [61]:
X = np.array([[1, 2, 3], [4, 5, 6]])
Y = np.array([[7, 8, 9], [10, 11,12]])
con = np.concatenate((X,Y))
rows = np.concatenate((X,Y),axis=1)
cols = np.concatenate((X,Y),axis =0 )
print("cols",cols)
print("rows=",rows)
print("=",con)

cols [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
rows= [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
filter_arr = (a > 20 ) & ( a < 70 )
a[filter_arr] = a[filter_arr] ** 2
print("a=",a)

a= [  10   20  900 1600 2500 3600   70   80]


In [42]:
a = np.eye(3) * 5
b = np.ones((3,3))
result = np.vstack((a,b))
print(result)

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
arr = np.array([1.2, np.nan, 3.8, 4.5, np.nan, 2.1]) 
clean_arr = arr[~np.isnan(arr)]
print(clean_arr)

[1.2 3.8 4.5 2.1]


In [49]:
a = np.linspace(0, 100, 10).astype(int)
values,counts = np.unique(a,return_counts =True)
print(len(values),counts)

10 [1 1 1 1 1 1 1 1 1 1]


In [51]:
data = np.array([[15, 88, 42], [91, 23, 67], [54, 76, 12]]) 
new_arr = np.where(data >= 50 ) == 1
print(new_arr)

False


In [52]:
data = np.array([[15, 88, 42], [91, 23, 67], [54, 76, 12]])
result = np.where(data>=50,1,0)
print(result)

[[0 1 0]
 [1 0 1]
 [1 1 0]]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
col_r = np.sum(a,axis=1),np.sum(a,axis=0)
print (col_r)

(array([ 6, 15]), array([5, 7, 9]))


In [14]:
arr = np.array([[10, 25, 30], [45, 50, 15]])
mean_value = np.mean(arr,axis = 0)
print(mean_value)

[27.5 37.5 22.5]


In [15]:
sales = np.array([100, 500, 250, 800]) 
price = np.where(sales>300 ,"High","low")
print(price)

['low' 'High' 'low' 'High']


In [24]:
sales = np.array([500, 100, 800, 300]) 
order = np.argsort(sales)
print(order)

[1 3 0 2]


In [28]:
sales = np.array([500, 100, 800, 300]) 
order = np.argsort(sales)[::-1]
print(order)

[2 0 3 1]


In [29]:
ratings = np.array([5, 4, 5, 3, 4, 5, 2])
unique_rating , counts = np.unique(ratings , return_counts = True)
print("unique_rating=",unique_rating)
print("count=" , counts)

unique_rating= [2 3 4 5]
count= [1 1 2 3]


In [31]:
np.random.seed(42)
data = np.random.randint(1,101,5)
print("data=",data)

data= [52 93 15 72 61]


In [32]:
np.random.seed(42)
data = np.random.randint(1,101,5)
print("data=",data)

data= [52 93 15 72 61]


In [34]:
np.random.seed(42)
data = np.random.rand(5)
print(data)
print(data.dtype)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
float64


In [36]:
item = [10, 20, 30]
data = np.random.choice(item , size = 5 , replace = True)
print(data)

[30 30 30 10 30]


In [37]:
item = [10, 20, 30]
data = np.random.choice(item , size = 6 , replace = True)
print(data)

[20 10 20 20 20 20]


In [38]:
a = np.array([10, np.nan, 30, 40])
missing_value = np.isnan(a)
print(missing_value)

[False  True False False]


In [39]:
a = np.array([10, np.nan, 30, 40])
a_sum = np.nansum(a)
mean_a = np.nanmean(a)
print("a=",a)
print("sum=",a_sum)
print("mean=",mean_a)

a= [10. nan 30. 40.]
sum= 80.0
mean= 26.666666666666668


In [40]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
join_vertically = np.vstack((x,y))
print("join=",join_vertically)

join= [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
join_h = np.hstack((x,y))
print("join hori=",join_h)

join hori= [[1 2 5 6]
 [3 4 7 8]]


In [43]:
a = np.array([1, 2,3])
copy = a.copy()
copy[0] = 0
view = a.view()
view[1]=9
print("data=",a)
print("copy=",copy)
print("view=",view)

data= [1 9 3]
copy= [0 2 3]
view= [1 9 3]


In [50]:
a = np.array([1, 2,3])
ravel_value = a.ravel()
ravel_value[0] = 8
print("Data=",a)
print("flatten_value=",ravel_value)

Data= [8 2 3]
flatten_value= [8 2 3]


In [49]:
a = np.array([1, 2,3])
flatten_value = a.flatten()
flatten_value[0] = 5
print("data=",a)
print("flat_value=",flatten_value)

data= [1 2 3]
flat_value= [5 2 3]


In [55]:
data = np.array([12, 45, 67, 23, 89, 34, 90])
filter_value = data[(data>30) & (data<80)]
print(filter_value)

[45 67 34]


In [57]:
prices = np.array([19.99, 5.50, 100.0, 45.25])
data_type = prices.astype(int)
print("prices=",prices)
print("data_type=",data_type)

prices= [ 19.99   5.5  100.    45.25]
data_type= [ 19   5 100  45]


In [60]:
m = np.array([[10, 50, 30], [20, 80, 40],[70, 60, 90]])
matrix = m.reshape(3,3)
med_value = np.median(matrix,axis = 1)
print("data=",m)
print("matrix=",matrix)
print("med_value",med_value)

data= [[10 50 30]
 [20 80 40]
 [70 60 90]]
matrix= [[10 50 30]
 [20 80 40]
 [70 60 90]]
med_value [30. 40. 70.]


In [61]:
m = np.array([[10, 50, 30], [20, 80, 40],[70, 60, 90]])
matrix = m.reshape(3,3)
med_value = np.median(matrix,axis = 0)
print("data=",m)
print("matrix=",matrix)
print("med_value",med_value)

data= [[10 50 30]
 [20 80 40]
 [70 60 90]]
matrix= [[10 50 30]
 [20 80 40]
 [70 60 90]]
med_value [20. 60. 40.]


In [70]:
scores = np.array([88, 92, 79, 93, 85, 92, 79])
unique_score = np.unique(scores)[::-1]
print(unique_score)

[93 92 88 85 79]


In [73]:
arr = np.array([-5, 10, -15, 20, -25])
rep = np.where(arr<0,0,arr )
print(rep)

[ 0 10  0 20  0]


In [3]:
a = np.arange(1,17).reshape(4,4)
print(a)
s = a[1:3,1:3]
print(s)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]


In [4]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("data=",arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

data= [[10 20 30]
 [40 50 60]]
2
(2, 3)
6


In [7]:
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [8]:
arr = np.zeros(8)
arr_1 = np.ones((3,3))
print(arr)
print(arr_1)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
integer = np.full((4,2),7)
print(integer)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [10]:
id = np.eye(4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
sp = np.linspace(0,1,5)
print(sp)

[0.   0.25 0.5  0.75 1.  ]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
first = arr[0]
last = arr[-1]
print("First=",first)
print("last=",last)

First= 10
last= 50


In [14]:
arr = np.array([10, 20, 30, 40, 50, 60])
slice_out = arr[1:4]
print(slice_out)

[20 30 40]


In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
row_col = a[0,1]
print("rc=",row_col)

[[1 2 3]
 [4 5 6]]
rc= 2


In [43]:
a = np.array([[10, 20, 30], [40, 50, 60]])
second_col = a[0:2,1:2]
print(second_col)

[[20]
 [50]]


In [44]:
a = np.array([[10, 20, 30], [40, 50, 60]])
second_col = a[:,1]
print(second_col)

[20 50]


In [45]:
arr = np.arange(1, 13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])
f = a.flatten()
print(f)

[1 2 3 4 5 6]


In [48]:
arr = np.array([1, 2, 3])
arr_1 = arr.astype(float)
print(arr.dtype)
print(arr_1)

int64
[1. 2. 3.]


In [4]:
a = np.array([10, 20, 30])
addition = a + 2
multiply = a*2
square = a*a
cube = a*a*a
print(a)
print("add=",addition)
print("multiply=",multiply)
print("square=",square)
print("cube=",cube)

[10 20 30]
add= [12 22 32]
multiply= [20 40 60]
square= [100 400 900]
cube= [ 1000  8000 27000]


In [6]:
sales = np.array([100, 200, 150, 300, 250])
sum_value = np.sum(sales)
mean_value = np.mean(sales)
max_value = np.max(sales)
min_value = np.min(sales)
med_value = np.median(sales)
print("sum",sum_value)
print("mean",mean_value)
print("max",max_value)
print("min",min_value)
print("med",med_value)

sum 1000
mean 200.0
max 300
min 100
med 200.0


In [9]:
sales = np.array([100, 200, 150, 300,250])
std_der = np.std(sales)
variance = np.var(sales)
print("standard deviation=",std_der)
print("variance=",variance)

standard deviation= 70.71067811865476
variance= 5000.0


In [11]:
sales = np.array([100, 500, 250, 800, 150])
bool_filtering = sales[sales>300]
print(bool_filtering)

[500 800]


In [12]:
sales = np.array([500, 100, 800, 300])
sorted_arr = np.sort(sales)
print("sales=",sales)
print("sorted=",sorted_arr)

sales= [500 100 800 300]
sorted= [100 300 500 800]


In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
join = np.concatenate((a,b))
print("joined arr=",join)

joined arr= [1 2 3 4 5 6]
